<?php
require 'vendor/autoload.php';
$app = require_once 'bootstrap/app.php';
$app->make('Illuminate\Contracts\Console\Kernel')->bootstrap();

$logoUrl = 'https://user.aplusdigitising.com/images/logo.png';
$primaryColor = '#F26522';

function wrapBody(string $content, string $logoUrl, string $primaryColor): string {
    return '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"></head><body style="margin:0;padding:0;background:#f4f6f8;font-family:Arial,Helvetica,sans-serif;color:#17212a;"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td align="center" style="padding:24px 16px;"><table role="presentation" width="600" cellspacing="0" cellpadding="0" style="width:100%;max-width:600px;background:#ffffff;border:1px solid #e2e8f0;border-radius:12px;overflow:hidden;"><tr><td style="padding:28px 28px 0;text-align:center;"><img src="'.$logoUrl.'" alt="{{site_label}}" style="max-width:180px;height:auto;margin-bottom:16px;"></td></tr><tr><td style="padding:0 28px 28px;font-size:14px;line-height:22px;">' . $content . '<p style="margin-bottom:0;">Need help? Contact <a href="mailto:{{support_email}}" style="color:#0d6ea3;">{{support_email}}</a>.</p></td></tr><tr><td style="padding:16px 28px;font-size:12px;color:#888888;background:#f8fafc;border-top:1px solid #e2e8f0;text-align:center;">{{site_label}} &bull; Questions? <a href="mailto:{{support_email}}" style="color:#0d6ea3;">{{support_email}}</a></td></tr></table></td></tr></table></body></html>';
}

$templates = [
    'Customer Account Activation' => [
        'subject' => 'Activate your account — {{site_label}}',
        'body' => '<p>Hello {{customer_name}},</p><p>Thank you for creating an account with {{site_label}}. Please activate your account by clicking the button below.</p><p style="text-align:center;margin:24px 0;"><a href="{{activation_url}}" style="display:inline-block;background:'.$primaryColor.';color:#ffffff;padding:12px 28px;text-decoration:none;border-radius:6px;font-weight:700;font-size:14px;">Activate Account</a></p><p>This link will expire at {{expires_at}}.</p><p>If you did not create this account, you can safely ignore this email.</p>',
    ],
    'Customer Password Reset' => [
        'subject' => 'Reset your password — {{site_label}}',
        'body' => '<p>Hello {{customer_name}},</p><p>We received a request to reset the password for your account on {{site_label}}.</p><p style="text-align:center;margin:24px 0;"><a href="{{reset_url}}" style="display:inline-block;background:'.$primaryColor.';color:#ffffff;padding:12px 28px;text-decoration:none;border-radius:6px;font-weight:700;font-size:14px;">Reset Password</a></p><p>This link will expire at {{expires_at}}.</p><p>If you did not request a password reset, you can safely ignore this email.</p>',
    ],
    'Customer Digitizing Order Confirmation' => [
        'subject' => 'Your digitizing order has been received — {{site_label}}',
        'body' => '<p>Hello {{customer_name}},</p><p>We have received your digitizing order and it is now in our production workflow.</p><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border-collapse:collapse;margin:16px 0;border:1px solid #e2e8f0;"><tr><td style="padding:10px 14px;font-size:13px;background:#f8fafc;border-bottom:1px solid #e2e8f0;"><strong>Reference ID</strong></td><td style="padding:10px 14px;font-size:13px;border-bottom:1px solid #e2e8f0;">{{order_id}}</td></tr><tr><td style="padding:10px 14px;font-size:13px;background:#f8fafc;border-bottom:1px solid #e2e8f0;"><strong>Design Name</strong></td><td style="padding:10px 14px;font-size:13px;border-bottom:1px solid #e2e8f0;">{{design_name}}</td></tr><tr><td style="padding:10px 14px;font-size:13px;background:#f8fafc;border-bottom:1px solid #e2e8f0;"><strong>Format</strong></td><td style="padding:10px 14px;font-size:13px;border-bottom:1px solid #e2e8f0;">{{format}}</td></tr><tr><td style="padding:10px 14px;font-size:13px;background:#f8fafc;border-bottom:1px solid #e2e8f0;"><strong>Turnaround</strong></td><td style="padding:10px 14px;font-size:13px;border-bottom:1px solid #e2e8f0;">{{turnaround}}</td></tr><tr><td style="padding:10px 14px;font-size:13px;background:#f8fafc;"><strong>Amount</strong></td><td style="padding:10px 14px;font-size:13px;">{{amount}}</td></tr></table><p style="text-align:center;margin:24px 0;"><a href="{{orders_url}}" style="display:inline-block;background:'.$primaryColor.';color:#ffffff;padding:12px 28px;text-decoration:none;border-radius:6px;font-weight:700;font-size:14px;">View My Orders</a></p>',
    ],
    'Customer Vector Order Confirmation' => [
        'subject' => 'Your vector order has been received — {{site_label}}',
        'body' => '<p>Hello {{customer_name}},</p><p>We have received your vector order and it is now in our production workflow.</p><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border-collapse:collapse;margin:16px 0;border:1px solid #e2e8f0;"><tr><td style="padding:10px 14px;font-size:13px;background:#f8fafc;border-bottom:1px solid #e2e8f0;"><strong>Reference ID</strong></td><td style="padding:10px 14px;font-size:13px;border-bottom:1px solid #e2e8f0;">{{order_id}}</td></tr><tr><td style="padding:10px 14px;font-size:13px;background:#f8fafc;border-bottom:1px solid #e2e8f0;"><strong>Design Name</strong></td><td style="padding:10px 14px;font-size:13px;border-bottom:1px solid #e2e8f0;">{{design_name}}</td></tr><tr><td style="padding:10px 14px;font-size:13px;background:#f8fafc;border-bottom:1px solid #e2e8f0;"><strong>Format</strong></td><td style="padding:10px 14px;font-size:13px;border-bottom:1px solid #e2e8f0;">{{format}}</td></tr><tr><td style="padding:10px 14px;font-size:13px;background:#f8fafc;border-bottom:1px solid #e2e8f0;"><strong>Turnaround</strong></td><td style="padding:10px 14px;font-size:13px;border-bottom:1px solid #e2e8f0;">{{turnaround}}</td></tr><tr><td style="padding:10px 14px;font-size:13px;background:#f8fafc;"><strong>Amount</strong></td><td style="padding:10px 14px;font-size:13px;">{{amount}}</td></tr></table><p style="text-align:center;margin:24px 0;"><a href="{{orders_url}}" style="display:inline-block;background:'.$primaryColor.';color:#ffffff;padding:12px 28px;text-decoration:none;border-radius:6px;font-weight:700;font-size:14px;">View My Orders</a></p>',
    ],
    'Customer Digitizing Quote Confirmation' => [
        'subject' => 'Your digitizing quote request has been received — {{site_label}}',
        'body' => '<p>Hello {{customer_name}},</p><p>We have received your digitizing quote request and our team will review it shortly.</p><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border-collapse:collapse;margin:16px 0;border:1px solid #e2e8f0;"><tr><td style="padding:10px 14px;font-size:13px;background:#f8fafc;border-bottom:1px solid #e2e8f0;"><strong>Reference ID</strong></td><td style="padding:10px 14px;font-size:13px;border-bottom:1px solid #e2e8f0;">{{order_id}}</td></tr><tr><td style="padding:10px 14px;font-size:13px;background:#f8fafc;border-bottom:1px solid #e2e8f0;"><strong>Design Name</strong></td><td style="padding:10px 14px;font-size:13px;border-bottom:1px solid #e2e8f0;">{{design_name}}</td></tr><tr><td style="padding:10px 14px;font-size:13px;background:#f8fafc;border-bottom:1px solid #e2e8f0;"><strong>Format</strong></td><td style="padding:10px 14px;font-size:13px;border-bottom:1px solid #e2e8f0;">{{format}}</td></tr><tr><td style="padding:10px 14px;font-size:13px;background:#f8fafc;border-bottom:1px solid #e2e8f0;"><strong>Turnaround</strong></td><td style="padding:10px 14px;font-size:13px;border-bottom:1px solid #e2e8f0;">{{turnaround}}</td></tr><tr><td style="padding:10px 14px;font-size:13px;background:#f8fafc;"><strong>Amount</strong></td><td style="padding:10px 14px;font-size:13px;">{{amount}}</td></tr></table><p style="text-align:center;margin:24px 0;"><a href="{{quotes_url}}" style="display:inline-block;background:'.$primaryColor.';color:#ffffff;padding:12px 28px;text-decoration:none;border-radius:6px;font-weight:700;font-size:14px;">View My Quotes</a></p>',
    ],
    'Customer Vector Quote Confirmation' => [
        'subject' => 'Your vector quote request has been received — {{site_label}}',
        'body' => '<p>Hello {{customer_name}},</p><p>We have received your vector quote request and our team will review it shortly.</p><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border-collapse:collapse;margin:16px 0;border:1px solid #e2e8f0;"><tr><td style="padding:10px 14px;font-size:13px;background:#f8fafc;border-bottom:1px solid #e2e8f0;"><strong>Reference ID</strong></td><td style="padding:10px 14px;font-size:13px;border-bottom:1px solid #e2e8f0;">{{order_id}}</td></tr><tr><td style="padding:10px 14px;font-size:13px;background:#f8fafc;border-bottom:1px solid #e2e8f0;"><strong>Design Name</strong></td><td style="padding:10px 14px;font-size:13px;border-bottom:1px solid #e2e8f0;">{{design_name}}</td></tr><tr><td style="padding:10px 14px;font-size:13px;background:#f8fafc;border-bottom:1px solid #e2e8f0;"><strong>Format</strong></td><td style="padding:10px 14px;font-size:13px;border-bottom:1px solid #e2e8f0;">{{format}}</td></tr><tr><td style="padding:10px 14px;font-size:13px;background:#f8fafc;border-bottom:1px solid #e2e8f0;"><strong>Turnaround</strong></td><td style="padding:10px 14px;font-size:13px;border-bottom:1px solid #e2e8f0;">{{turnaround}}</td></tr><tr><td style="padding:10px 14px;font-size:13px;background:#f8fafc;"><strong>Amount</strong></td><td style="padding:10px 14px;font-size:13px;">{{amount}}</td></tr></table><p style="text-align:center;margin:24px 0;"><a href="{{quotes_url}}" style="display:inline-block;background:'.$primaryColor.';color:#ffffff;padding:12px 28px;text-decoration:none;border-radius:6px;font-weight:700;font-size:14px;">View My Quotes</a></p>',
    ],
    'Customer Order Completed' => [
        'subject' => 'Your order with {{site_label}} has been completed',
        'body' => '<p>Hello {{customer_name}},</p><p>Great news — your order with {{site_label}} has been completed and is ready for your review.</p><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border-collapse:collapse;margin:16px 0;border:1px solid #e2e8f0;"><tr><td style="padding:10px 14px;font-size:13px;background:#f8fafc;border-bottom:1px solid #e2e8f0;"><strong>Reference ID</strong></td><td style="padding:10px 14px;font-size:13px;border-bottom:1px solid #e2e8f0;">{{order_id}}</td></tr><tr><td style="padding:10px 14px;font-size:13px;background:#f8fafc;border-bottom:1px solid #e2e8f0;"><strong>Design Name</strong></td><td style="padding:10px 14px;font-size:13px;border-bottom:1px solid #e2e8f0;">{{design_name}}</td></tr><tr><td style="padding:10px 14px;font-size:13px;background:#f8fafc;border-bottom:1px solid #e2e8f0;"><strong>Amount</strong></td><td style="padding:10px 14px;font-size:13px;border-bottom:1px solid #e2e8f0;">{{amount}}</td></tr><tr><td style="padding:10px 14px;font-size:13px;background:#f8fafc;"><strong>{{body_label}}</strong></td><td style="padding:10px 14px;font-size:13px;">{{stitches}}</td></tr></table><p style="text-align:center;margin:24px 0;"><a href="{{review_url}}" style="display:inline-block;background:'.$primaryColor.';color:#ffffff;padding:12px 28px;text-decoration:none;border-radius:6px;font-weight:700;font-size:14px;">Review Order</a></p><p style="font-size:13px;color:#64748b;margin-top:20px;padding:12px 16px;background:#f8fafc;border-left:3px solid '.$primaryColor.';"><strong>Disclaimer:</strong> Please conduct a test run and verify the sample against your design before proceeding with production. {{site_label}} is not responsible for any damage to materials incurred during use.</p>',
    ],
    'Customer Quote Completed' => [
        'subject' => 'Your quote from {{site_label}} is ready',
        'body' => '<p>Hello {{customer_name}},</p><p>Your quote from {{site_label}} is ready for your review.</p><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border-collapse:collapse;margin:16px 0;border:1px solid #e2e8f0;"><tr><td style="padding:10px 14px;font-size:13px;background:#f8fafc;border-bottom:1px solid #e2e8f0;"><strong>Reference ID</strong></td><td style="padding:10px 14px;font-size:13px;border-bottom:1px solid #e2e8f0;">{{order_id}}</td></tr><tr><td style="padding:10px 14px;font-size:13px;background:#f8fafc;"><strong>Design Name</strong></td><td style="padding:10px 14px;font-size:13px;">{{design_name}}</td></tr></table><p style="text-align:center;margin:24px 0;"><a href="{{review_url}}" style="display:inline-block;background:'.$primaryColor.';color:#ffffff;padding:12px 28px;text-decoration:none;border-radius:6px;font-weight:700;font-size:14px;">Review Quote</a></p><p style="font-size:13px;color:#64748b;margin-top:20px;padding:12px 16px;background:#f8fafc;border-left:3px solid '.$primaryColor.';"><strong>Please note:</strong> This quotation is a preliminary estimate only. Final pricing may vary up to +/-10% based on the final design output. Should the cost exceed this range, we will notify you for approval before proceeding.</p>',
    ],
    'Customer Quick Quote Completed' => [
        'subject' => 'Your quick quote from {{site_label}} is ready',
        'body' => '<p>Hello {{customer_name}},</p><p>Your quick quote from {{site_label}} is ready. You can review it and complete payment using the link below.</p><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border-collapse:collapse;margin:16px 0;border:1px solid #e2e8f0;"><tr><td style="padding:10px 14px;font-size:13px;background:#f8fafc;border-bottom:1px solid #e2e8f0;"><strong>Reference ID</strong></td><td style="padding:10px 14px;font-size:13px;border-bottom:1px solid #e2e8f0;">{{order_id}}</td></tr><tr><td style="padding:10px 14px;font-size:13px;background:#f8fafc;border-bottom:1px solid #e2e8f0;"><strong>Design Name</strong></td><td style="padding:10px 14px;font-size:13px;border-bottom:1px solid #e2e8f0;">{{design_name}}</td></tr><tr><td style="padding:10px 14px;font-size:13px;background:#f8fafc;"><strong>Amount</strong></td><td style="padding:10px 14px;font-size:13px;">{{amount}}</td></tr></table><p style="text-align:center;margin:24px 0;"><a href="{{review_url}}" style="display:inline-block;background:'.$primaryColor.';color:#ffffff;padding:12px 28px;text-decoration:none;border-radius:6px;font-weight:700;font-size:14px;">Review & Pay</a></p>',
    ],
    'Customer Quote Negotiation Response' => [
        'subject' => 'Your quote request has been reviewed — {{site_label}}',
        'body' => '<p>Hello {{customer_name}},</p><p>{{message}}</p><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border-collapse:collapse;margin:16px 0;border:1px solid #e2e8f0;"><tr><td style="padding:10px 14px;font-size:13px;background:#f8fafc;border-bottom:1px solid #e2e8f0;"><strong>Reference ID</strong></td><td style="padding:10px 14px;font-size:13px;border-bottom:1px solid #e2e8f0;">{{order_id}}</td></tr><tr><td style="padding:10px 14px;font-size:13px;background:#f8fafc;border-bottom:1px solid #e2e8f0;"><strong>Design Name</strong></td><td style="padding:10px 14px;font-size:13px;border-bottom:1px solid #e2e8f0;">{{design_name}}</td></tr><tr><td style="padding:10px 14px;font-size:13px;background:#f8fafc;"><strong>Current Amount</strong></td><td style="padding:10px 14px;font-size:13px;">{{amount}}</td></tr></table><p style="text-align:center;margin:24px 0;"><a href="{{review_url}}" style="display:inline-block;background:'.$primaryColor.';color:#ffffff;padding:12px 28px;text-decoration:none;border-radius:6px;font-weight:700;font-size:14px;">Review Quote</a></p>',
    ],
];

foreach ($templates as $name => $data) {
    $fullBody = wrapBody($data['body'], $logoUrl, $primaryColor);
    DB::table('email_templates')->where('template_name', $name)->update([
        'subject' => $data['subject'],
        'body' => $fullBody,
    ]);
    echo "Updated: $name" . PHP_EOL;
}

echo PHP_EOL . 'All email templates updated!' . PHP_EOL;
